### ISSUE TITLE
Allow judges to create/edit checkers for problems

### ISSUE THREAD

**Issue by lcastillov** [MatcomOnlineGrader/judge#51]
### 02/14/2023
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/4879115/218654034-5b03666e-2c79-45ef-9034-80f2e901ab90.png">

### 05/05/2023
<img width="1462" alt="image" src="https://user-images.githubusercontent.com/4879115/236692508-0ad64d2e-0072-4ef7-9946-fc5eabcc9baf.png">

**Tasks**:
- [ ] Crear una URL (get) para listar los checkers disponibles para un problema https://matcomgrader.com/problem/ID/checker 
- [ ] Crear un botón en la lista de checkers para cambiar la asignación del checker.
- [ ] Agregar la posibilidad de crear un checker nuevo para un problema.
